#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
test_reports.py

Comprehensive validation suite for all evaluation reports generated by the
RAG evaluation pipeline. Ensures correct JSON structure, valid numeric ranges,
schema consistency, cross-report alignment, and regression safety.
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

import numpy as np
import pandas as pd
import pytest
from unittest.mock import patch, MagicMock

# -----------------------------------------------------------------------------
# Import evaluation modules for schema references
# -----------------------------------------------------------------------------
try:
    from evaluation.accuracy_metrics import EvaluationRecord as AccuracyRecord
    from evaluation.latency_metrics import QuestionLatencyResult
    from evaluation.llm_judge import JudgementResult
    from evaluation.evaluation_runner import EvaluationResult
except ImportError as e:
    print(f"Import error: {e}. Ensure evaluation modules are in PYTHONPATH.", file=sys.stderr)
    raise

# -----------------------------------------------------------------------------
# Logging for test debug
# -----------------------------------------------------------------------------
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

# -----------------------------------------------------------------------------
# Fixtures: Sample report files in temporary directories
# -----------------------------------------------------------------------------

@pytest.fixture
def sample_accuracy_report_dict() -> Dict[str, Any]:
    """Return a valid accuracy report dictionary."""
    return {
        "summary": {
            "total": 10,
            "average_overall_score": 0.89,
            "type_counts": {"structured": 4, "semantic": 3, "hybrid": 3},
            "category_averages": {
                "structured": 0.92,
                "semantic": 0.87,
                "retrieval": 0.85,
                "hallucination": 0.90,
            },
            "timestamp": "2025-01-01T00:00:00",
        },
        "results": [
            {
                "question_id": "1",
                "question": "What is X?",
                "query_type": "structured",
                "generated_answer": "42",
                "expected_answer": 42,
                "retrieved_context": ["context1"],
                "metrics": [
                    {"metric_name": "exact_match", "score": 1.0, "passed": True, "details": {}, "timestamp": "now"}
                ],
                "overall_score": 0.95,
            },
            {
                "question_id": "2",
                "question": "Summarize Y.",
                "query_type": "semantic",
                "generated_answer": "Y is good.",
                "expected_answer": "Y is excellent.",
                "retrieved_context": ["context2"],
                "metrics": [
                    {"metric_name": "bleu", "score": 0.5, "passed": True, "details": {}, "timestamp": "now"}
                ],
                "overall_score": 0.85,
            },
        ],
    }


@pytest.fixture
def sample_latency_report_dict() -> Dict[str, Any]:
    """Return a valid latency report dictionary."""
    return {
        "summary": {
            "total_questions": 10,
            "total_time_sec": 120.5,
            "total_latency_ms_stats": {
                "mean": 850.0,
                "median": 820.0,
                "min": 600.0,
                "max": 1200.0,
                "std": 150.0,
                "p50": 820.0,
                "p90": 1100.0,
                "p95": 1150.0,
                "p99": 1180.0,
            },
            "stage_stats": {
                "llm_generation": {"mean": 600.0, "median": 590.0},
                "duckdb_retrieval": {"mean": 100.0, "median": 95.0},
                "qdrant_retrieval": {"mean": 120.0, "median": 115.0},
            },
            "throughput_qps": 0.083,
            "tokens_per_second": 30.0,
            "total_tokens": 3600,
            "peak_memory_mb": 2048.5,
            "average_cpu_percent": 45.2,
            "average_memory_percent": 60.1,
            "timestamp": "2025-01-01T00:00:00",
        },
        "results": [
            {
                "question_id": "1",
                "question": "What is X?",
                "query_type": "structured",
                "latencies": [
                    {"stage": "llm_generation", "duration_ms": 600, "metadata": {}}
                ],
                "total_latency_ms": 850.0,
                "token_count": 50,
                "tokens_per_second": 83.3,
                "throughput": 0.0,
                "timestamp": "2025-01-01T00:00:00",
            },
        ],
    }


@pytest.fixture
def sample_judge_report_dict() -> Dict[str, Any]:
    """Return a valid LLM judge report dictionary."""
    return {
        "summary": {
            "total": 10,
            "average_overall_score": 8.5,
            "median_overall_score": 8.6,
            "pass_rate": 0.9,
            "hallucination_rate": 0.05,
            "average_confidence": 0.87,
            "average_scores_by_dimension": {
                "accuracy": 8.7,
                "completeness": 8.1,
                "relevance": 8.9,
                "faithfulness": 8.4,
                "reasoning": 8.0,
            },
            "timestamp": "2025-01-01T00:00:00",
        },
        "results": [
            {
                "question_id": "1",
                "question": "What is X?",
                "query_type": "structured",
                "answer": "42",
                "context": ["context1"],
                "ground_truth": 42,
                "scores": [
                    {"score_name": "accuracy", "score": 9.0, "passed": True, "confidence": 0.9, "reason": "Good"}
                ],
                "overall_score": 8.8,
                "verdict": "pass",
                "timestamp": "2025-01-01T00:00:00",
            }
        ],
    }


@pytest.fixture
def sample_final_report_dict(sample_accuracy_report_dict, sample_latency_report_dict, sample_judge_report_dict) -> Dict[str, Any]:
    """Return a valid final aggregated report dictionary."""
    acc_summary = sample_accuracy_report_dict["summary"]
    lat_summary = sample_latency_report_dict["summary"]
    judge_summary = sample_judge_report_dict["summary"]

    acc_score = acc_summary["average_overall_score"] * 100  # 89
    lat_mean = lat_summary["total_latency_ms_stats"]["mean"]
    lat_score = max(0, 100 - (lat_mean - 100) / 10)
    lat_score = min(100, lat_score)
    judge_score = judge_summary["average_overall_score"] * 10  # 85

    overall = 0.5 * acc_score + 0.2 * lat_score + 0.3 * judge_score

    return {
        "summary": {
            "questions_evaluated": 10,
            "accuracy_score": acc_score,
            "latency_score": lat_score,
            "judge_score": judge_score,
            "hallucination_rate": judge_summary["hallucination_rate"],
            "average_latency_ms": lat_summary["total_latency_ms_stats"]["mean"],
            "overall_score": overall,
            "duration_seconds": 120.5,
            "timestamp": "2025-01-01T00:00:00",
            "metadata": {
                "accuracy_report": "accuracy_report.json",
                "latency_report": "latency_report.json",
                "judge_report": "llm_judge_report.json"
            }
        },
        "details": {
            "config": {"sample_size": 10, "seed": 42}
        }
    }


@pytest.fixture
def temp_report_dir(tmp_path, sample_accuracy_report_dict, sample_latency_report_dict,
                    sample_judge_report_dict, sample_final_report_dict) -> Path:
    """Create a temporary directory with all report files."""
    report_dir = tmp_path / "reports"
    report_dir.mkdir()
    with open(report_dir / "accuracy_report.json", "w") as f:
        json.dump(sample_accuracy_report_dict, f)
    with open(report_dir / "latency_report.json", "w") as f:
        json.dump(sample_latency_report_dict, f)
    with open(report_dir / "llm_judge_report.json", "w") as f:
        json.dump(sample_judge_report_dict, f)
    with open(report_dir / "final_report.json", "w") as f:
        json.dump(sample_final_report_dict, f)
    return report_dir


# -----------------------------------------------------------------------------
# Utility functions for validation
# -----------------------------------------------------------------------------

def validate_numeric_range(value: Union[int, float], min_val: float, max_val: float, name: str = "value") -> None:
    """Assert that a numeric value is within [min_val, max_val]."""
    assert min_val <= value <= max_val, f"{name} = {value} outside range [{min_val}, {max_val}]"

def validate_non_negative(value: Union[int, float], name: str = "value") -> None:
    """Assert that a numeric value is >= 0."""
    assert value >= 0, f"{name} = {value} is negative"

def validate_required_keys(data: Dict[str, Any], required_keys: List[str], context: str = "") -> None:
    """Assert that all required keys exist in the dictionary."""
    for key in required_keys:
        assert key in data, f"Missing required key '{key}' in {context}"

# -----------------------------------------------------------------------------
# Test Classes
# -----------------------------------------------------------------------------

class TestAccuracyReportValidation:
    """Validate accuracy_report.json structure and content."""

    def test_accuracy_report_has_required_keys(self, sample_accuracy_report_dict):
        data = sample_accuracy_report_dict
        validate_required_keys(data, ["summary", "results"], "accuracy_report root")
        validate_required_keys(data["summary"], ["total", "average_overall_score", "type_counts", "category_averages"], "summary")
        assert isinstance(data["results"], list)
        for result in data["results"]:
            validate_required_keys(result, ["question_id", "question", "query_type", "overall_score"], "result item")

    def test_accuracy_report_score_ranges(self, sample_accuracy_report_dict):
        summary = sample_accuracy_report_dict["summary"]
        validate_numeric_range(summary["average_overall_score"], 0.0, 1.0, "average_overall_score")
        for result in sample_accuracy_report_dict["results"]:
            validate_numeric_range(result["overall_score"], 0.0, 1.0, "overall_score")
            for metric in result.get("metrics", []):
                if "score" in metric:
                    validate_numeric_range(metric["score"], 0.0, 1.0, f"metric {metric.get('metric_name')}")

    def test_accuracy_report_question_count_consistency(self, sample_accuracy_report_dict):
        summary = sample_accuracy_report_dict["summary"]
        results = sample_accuracy_report_dict["results"]
        assert len(results) == summary["total"]
        type_counts = summary["type_counts"]
        count_from_results = {t: 0 for t in ["structured", "semantic", "hybrid"]}
        for r in results:
            count_from_results[r["query_type"]] += 1
        assert type_counts["structured"] == count_from_results["structured"]
        assert type_counts["semantic"] == count_from_results["semantic"]
        assert type_counts["hybrid"] == count_from_results["hybrid"]

    def test_accuracy_report_no_null_values(self, sample_accuracy_report_dict):
        def check_no_none(obj):
            if isinstance(obj, dict):
                for v in obj.values():
                    check_no_none(v)
            elif isinstance(obj, list):
                for item in obj:
                    check_no_none(item)
            else:
                assert obj is not None, "Found None value"
        check_no_none(sample_accuracy_report_dict)

    def test_accuracy_report_metric_passed_correct(self, sample_accuracy_report_dict):
        for result in sample_accuracy_report_dict["results"]:
            for metric in result.get("metrics", []):
                if "score" in metric and "passed" in metric:
                    assert isinstance(metric["passed"], bool)


class TestLatencyReportValidation:
    """Validate latency_report.json structure and content."""

    def test_latency_report_has_required_keys(self, sample_latency_report_dict):
        data = sample_latency_report_dict
        validate_required_keys(data, ["summary", "results"], "latency_report")
        summary = data["summary"]
        validate_required_keys(summary, [
            "total_questions", "total_time_sec", "total_latency_ms_stats",
            "throughput_qps", "tokens_per_second", "total_tokens"
        ], "latency summary")
        for result in data["results"]:
            validate_required_keys(result, ["question_id", "question", "total_latency_ms", "latencies"], "latency result")

    def test_latency_report_numeric_ranges(self, sample_latency_report_dict):
        summary = sample_latency_report_dict["summary"]
        stats = summary["total_latency_ms_stats"]
        for key in ["mean", "median", "min", "max", "std", "p50", "p90", "p95", "p99"]:
            if key in stats:
                validate_non_negative(stats[key], f"latency stat {key}")
        assert stats["p50"] <= stats["p90"] <= stats["p95"] <= stats["p99"], "Percentiles not monotonic"
        validate_non_negative(summary["throughput_qps"], "throughput_qps")
        validate_non_negative(summary["tokens_per_second"], "tokens_per_second")
        validate_non_negative(summary["total_tokens"], "total_tokens")
        for result in sample_latency_report_dict["results"]:
            stage_sum = sum(l["duration_ms"] for l in result["latencies"])
            assert abs(result["total_latency_ms"] - stage_sum) < 1e-6, f"Total latency mismatch in {result['question_id']}"

    def test_latency_report_stage_timing_presence(self, sample_latency_report_dict):
        summary = sample_latency_report_dict["summary"]
        if "stage_stats" in summary:
            stages = summary["stage_stats"]
            assert "llm_generation" in stages
        for result in sample_latency_report_dict["results"]:
            for stage in result["latencies"]:
                assert "stage" in stage
                assert "duration_ms" in stage

    def test_latency_report_question_count_consistency(self, sample_latency_report_dict):
        summary = sample_latency_report_dict["summary"]
        results = sample_latency_report_dict["results"]
        assert len(results) == summary["total_questions"]

    def test_latency_report_total_time_calc(self, sample_latency_report_dict):
        assert sample_latency_report_dict["summary"]["total_time_sec"] > 0


class TestLLMJudgeReportValidation:
    """Validate llm_judge_report.json structure and content."""

    def test_judge_report_has_required_keys(self, sample_judge_report_dict):
        data = sample_judge_report_dict
        validate_required_keys(data, ["summary", "results"], "judge_report")
        summary = data["summary"]
        validate_required_keys(summary, [
            "total", "average_overall_score", "pass_rate", "hallucination_rate", "average_confidence"
        ], "judge summary")
        for result in data["results"]:
            validate_required_keys(result, ["question_id", "question", "query_type", "overall_score", "scores", "verdict"], "judge result")

    def test_judge_report_score_ranges(self, sample_judge_report_dict):
        summary = sample_judge_report_dict["summary"]
        validate_numeric_range(summary["average_overall_score"], 0.0, 10.0, "average_overall_score")
        validate_numeric_range(summary["hallucination_rate"], 0.0, 1.0, "hallucination_rate")
        validate_numeric_range(summary["pass_rate"], 0.0, 1.0, "pass_rate")
        validate_numeric_range(summary["average_confidence"], 0.0, 1.0, "average_confidence")
        for result in sample_judge_report_dict["results"]:
            validate_numeric_range(result["overall_score"], 0.0, 10.0, "overall_score")
            for score in result["scores"]:
                validate_numeric_range(score["score"], 0.0, 10.0, f"score {score.get('score_name')}")
                validate_numeric_range(score["confidence"], 0.0, 1.0, "confidence")

    def test_judge_report_verdict_matches_score(self, sample_judge_report_dict):
        for result in sample_judge_report_dict["results"]:
            overall = result["overall_score"]
            verdict = result["verdict"]
            if overall >= 6.0:
                assert verdict == "pass" or verdict == "uncertain", f"Verdict {verdict} but score {overall} >= 6"
            elif overall < 4.0:
                assert verdict == "fail" or verdict == "uncertain", f"Verdict {verdict} but score {overall} < 4"

    def test_judge_report_consistency_scores_vs_summary(self, sample_judge_report_dict):
        results = sample_judge_report_dict["results"]
        summary = sample_judge_report_dict["summary"]
        computed_avg = np.mean([r["overall_score"] for r in results])
        assert abs(computed_avg - summary["average_overall_score"]) < 1e-6, "Average overall score mismatch"

    def test_judge_report_hallucination_rate(self, sample_judge_report_dict):
        results = sample_judge_report_dict["results"]
        hallucinated = 0
        for r in results:
            for s in r["scores"]:
                if s["score_name"] == "hallucination" and s["score"] < 5.0:
                    hallucinated += 1
                    break
        expected_rate = hallucinated / len(results) if results else 0.0
        summary = sample_judge_report_dict["summary"]
        assert abs(expected_rate - summary["hallucination_rate"]) < 1e-6, "Hallucination rate mismatch"


class TestFinalReportValidation:
    """Validate final_report.json structure and content."""

    def test_final_report_has_required_keys(self, sample_final_report_dict):
        data = sample_final_report_dict
        validate_required_keys(data, ["summary", "details"], "final_report")
        summary = data["summary"]
        validate_required_keys(summary, [
            "questions_evaluated", "accuracy_score", "latency_score", "judge_score",
            "hallucination_rate", "average_latency_ms", "overall_score", "duration_seconds"
        ], "final summary")

    def test_final_report_score_ranges(self, sample_final_report_dict):
        summary = sample_final_report_dict["summary"]
        validate_numeric_range(summary["accuracy_score"], 0.0, 100.0, "accuracy_score")
        validate_numeric_range(summary["latency_score"], 0.0, 100.0, "latency_score")
        validate_numeric_range(summary["judge_score"], 0.0, 100.0, "judge_score")
        validate_numeric_range(summary["overall_score"], 0.0, 100.0, "overall_score")
        validate_numeric_range(summary["hallucination_rate"], 0.0, 1.0, "hallucination_rate")
        validate_non_negative(summary["average_latency_ms"], "average_latency_ms")
        validate_non_negative(summary["duration_seconds"], "duration_seconds")

    def test_final_report_weighted_score_calculation(self, sample_final_report_dict):
        summary = sample_final_report_dict["summary"]
        weights = {"accuracy": 0.5, "latency": 0.2, "judge": 0.3}
        expected = (
            weights["accuracy"] * summary["accuracy_score"] +
            weights["latency"] * summary["latency_score"] +
            weights["judge"] * summary["judge_score"]
        )
        assert abs(summary["overall_score"] - expected) < 1e-6, f"Expected {expected}, got {summary['overall_score']}"

    def test_final_report_metadata_integrity(self, sample_final_report_dict):
        details = sample_final_report_dict.get("details", {})
        if "config" in details:
            config = details["config"]
            assert "sample_size" in config
            assert "seed" in config


class TestCrossReportConsistency:
    """Validate consistency across different report types."""

    def test_question_count_consistency(self, temp_report_dir):
        acc_path = temp_report_dir / "accuracy_report.json"
        lat_path = temp_report_dir / "latency_report.json"
        judge_path = temp_report_dir / "llm_judge_report.json"
        final_path = temp_report_dir / "final_report.json"

        with open(acc_path) as f:
            acc_data = json.load(f)
        with open(lat_path) as f:
            lat_data = json.load(f)
        with open(judge_path) as f:
            judge_data = json.load(f)
        with open(final_path) as f:
            final_data = json.load(f)

        acc_count = acc_data["summary"]["total"]
        lat_count = lat_data["summary"]["total_questions"]
        judge_count = judge_data["summary"]["total"]
        final_count = final_data["summary"]["questions_evaluated"]

        assert acc_count == lat_count == judge_count == final_count, "Question counts mismatch across reports"

    def test_question_ids_match_across_reports(self, temp_report_dir):
        acc_path = temp_report_dir / "accuracy_report.json"
        lat_path = temp_report_dir / "latency_report.json"
        judge_path = temp_report_dir / "llm_judge_report.json"

        with open(acc_path) as f:
            acc_data = json.load(f)
        with open(lat_path) as f:
            lat_data = json.load(f)
        with open(judge_path) as f:
            judge_data = json.load(f)

        acc_ids = {r["question_id"] for r in acc_data["results"]}
        lat_ids = {r["question_id"] for r in lat_data["results"]}
        judge_ids = {r["question_id"] for r in judge_data["results"]}

        assert acc_ids == lat_ids == judge_ids, "Question ID sets differ across reports"

    def test_accuracy_and_judge_scores_correlation(self, temp_report_dir):
        acc_path = temp_report_dir / "accuracy_report.json"
        judge_path = temp_report_dir / "llm_judge_report.json"

        with open(acc_path) as f:
            acc_data = json.load(f)
        with open(judge_path) as f:
            judge_data = json.load(f)

        acc_scores = {r["question_id"]: r["overall_score"] for r in acc_data["results"]}
        judge_scores = {r["question_id"]: r["overall_score"] for r in judge_data["results"]}

        for qid in acc_scores:
            acc = acc_scores[qid] * 10  # accuracy is 0-1, judge is 0-10
            judge = judge_scores[qid]
            assert abs(acc - judge) <= 6.0, f"Large discrepancy for question {qid}: acc={acc}, judge={judge}"

    def test_latency_and_final_latency_match(self, temp_report_dir):
        lat_path = temp_report_dir / "latency_report.json"
        final_path = temp_report_dir / "final_report.json"

        with open(lat_path) as f:
            lat_data = json.load(f)
        with open(final_path) as f:
            final_data = json.load(f)

        lat_mean = lat_data["summary"]["total_latency_ms_stats"]["mean"]
        final_avg = final_data["summary"]["average_latency_ms"]
        assert abs(lat_mean - final_avg) < 1e-6, "Latency mean mismatch between latency and final reports"


class TestReportRegressionSafety:
    """Test backward compatibility and schema evolution."""

    def test_accuracy_report_handles_missing_optional_fields(self, sample_accuracy_report_dict):
        data = sample_accuracy_report_dict
        if data["results"][0]["metrics"]:
            data["results"][0]["metrics"][0].pop("details", None)
        validate_required_keys(data, ["summary", "results"], "accuracy_report root")
        # No assertion, just ensure no exception.

    def test_latency_report_handles_missing_stage_stats(self):
        data = {
            "summary": {
                "total_questions": 1,
                "total_time_sec": 10,
                "total_latency_ms_stats": {"mean": 100, "median": 100},
                "throughput_qps": 0.1,
                "tokens_per_second": 10,
                "total_tokens": 10,
            },
            "results": []
        }
        validate_required_keys(data, ["summary", "results"], "latency_report")
        # No stage_stats check; should pass.

    def test_final_report_handles_additional_metadata(self, sample_final_report_dict):
        sample_final_report_dict["summary"]["extra_field"] = "some value"
        validate_required_keys(sample_final_report_dict["summary"], [
            "questions_evaluated", "accuracy_score", "latency_score", "judge_score",
            "hallucination_rate", "average_latency_ms", "overall_score", "duration_seconds"
        ], "final summary")
        # No exception.

    def test_report_files_exist_and_readable(self, temp_report_dir):
        report_paths = [
            temp_report_dir / "accuracy_report.json",
            temp_report_dir / "latency_report.json",
            temp_report_dir / "llm_judge_report.json",
            temp_report_dir / "final_report.json",
        ]
        for path in report_paths:
            assert path.exists(), f"Report file {path} missing"
            with open(path) as f:
                data = json.load(f)
                assert isinstance(data, dict), f"Report {path} is not a valid JSON object"


# -----------------------------------------------------------------------------
# Test Edge Cases: Corrupted or empty reports
# -----------------------------------------------------------------------------

def test_corrupted_accuracy_report_raises_error(tmp_path):
    path = tmp_path / "accuracy_report.json"
    path.write_text("{corrupted json")
    with pytest.raises(json.JSONDecodeError):
        with open(path) as f:
            json.load(f)

def test_empty_accuracy_report(tmp_path):
    path = tmp_path / "accuracy_report.json"
    path.write_text("{}")
    with open(path) as f:
        data = json.load(f)
    with pytest.raises(AssertionError):
        validate_required_keys(data, ["summary", "results"], "accuracy_report root")

def test_accuracy_report_with_zero_questions(tmp_path):
    data = {"summary": {"total": 0, "average_overall_score": 0.0}, "results": []}
    path = tmp_path / "accuracy_report.json"
    with open(path, "w") as f:
        json.dump(data, f)
    with open(path) as f:
        loaded = json.load(f)
    assert loaded["summary"]["total"] == 0
    assert len(loaded["results"]) == 0

# -----------------------------------------------------------------------------
# Additional sanity checks
# -----------------------------------------------------------------------------

def test_final_report_has_consistent_values_with_source_reports(temp_report_dir):
    acc_path = temp_report_dir / "accuracy_report.json"
    lat_path = temp_report_dir / "latency_report.json"
    judge_path = temp_report_dir / "llm_judge_report.json"
    final_path = temp_report_dir / "final_report.json"

    with open(acc_path) as f:
        acc = json.load(f)
    with open(lat_path) as f:
        lat = json.load(f)
    with open(judge_path) as f:
        judge = json.load(f)
    with open(final_path) as f:
        final = json.load(f)

    assert final["summary"]["hallucination_rate"] == judge["summary"]["hallucination_rate"], "Hallucination rate mismatch"
    assert final["summary"]["average_latency_ms"] == lat["summary"]["total_latency_ms_stats"]["mean"], "Average latency mismatch"


# -----------------------------------------------------------------------------
# Run tests if executed directly
# -----------------------------------------------------------------------------

if __name__ == "__main__":
    pytest.main([__file__, "-v"])